apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: fake-init
        image: busybox:1.28
        args:
        - sleep
        - "20"
      restartPolicy: Never
  backoffLimit: 4
