apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: delay
        image: busybox:1.28
        args:
        - sleep
        - "1000"
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
